# This is a basic workflow to help you get started with Actions

name: Check pr description image

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

permissions:
  issues: 'write'

jobs:
  check-pr-description-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const script = require('./.github/workflows/scripts/pr-description-check.ts')
            await script({github, context, core})
