# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-pr-description-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Comment PR
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ github.token }}
          script: |
            const script = require('./.github/workflows/scripts/pr-description-check.ts')
            await script({github, context, core})
